apiVersion: v2
name: splunk-otel-collector
version: 0.72.0
appVersion: 0.75.0
description: Splunk OpenTelemetry Collector for Kubernetes
icon: https://github.com/signalfx/splunk-otel-collector-chart/tree/main/splunk.png
type: application
keywords:
- splunk
- opentelemetry
- observability
- logs
- traces
- metrics
- apm
maintainers:
- name: dmitryax
- name: jvoravong
- name: emaderer
dependencies:
  - name: opentelemetry-operator
    version: 0.24.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    alias: operator
    condition: operator.enabled
